# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DotenvCli < Formula
  desc "Secure environment variable management CLI"
  homepage "https://dotenv.cloud"
  version "1.4.0"
  license "MIT"

  depends_on "ca-certificates" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dotenvcloud/cli/releases/download/v1.4.0/dotenv-cli_1.4.0_darwin_amd64.tar.gz"
      sha256 "26f5a0531e0c8547dc0a496a9e90dae2156c3dc313830da081c8b1155e08183b"

      define_method(:install) do
        bin.install "dotenv"

        bash_completion.install "completions/dotenv.bash" => "dotenv"
        zsh_completion.install "completions/dotenv.zsh" => "_dotenv"
        fish_completion.install "completions/dotenv.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dotenvcloud/cli/releases/download/v1.4.0/dotenv-cli_1.4.0_darwin_arm64.tar.gz"
      sha256 "3ec804c75a9f1c3aa19ba534d9d60314ec72dd917933715494e8a6937df900e9"

      define_method(:install) do
        bin.install "dotenv"

        bash_completion.install "completions/dotenv.bash" => "dotenv"
        zsh_completion.install "completions/dotenv.zsh" => "_dotenv"
        fish_completion.install "completions/dotenv.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dotenvcloud/cli/releases/download/v1.4.0/dotenv-cli_1.4.0_linux_amd64.tar.gz"
      sha256 "788e1b0db117d5b8567b2f99b9d2ebc57162d893ad699cc86fa1865e94819272"
      define_method(:install) do
        bin.install "dotenv"

        bash_completion.install "completions/dotenv.bash" => "dotenv"
        zsh_completion.install "completions/dotenv.zsh" => "_dotenv"
        fish_completion.install "completions/dotenv.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dotenvcloud/cli/releases/download/v1.4.0/dotenv-cli_1.4.0_linux_arm64.tar.gz"
      sha256 "fcbe121a96ba6d5f81bf20c580d71d70297baa8d13a7668420238e298f227263"
      define_method(:install) do
        bin.install "dotenv"

        bash_completion.install "completions/dotenv.bash" => "dotenv"
        zsh_completion.install "completions/dotenv.zsh" => "_dotenv"
        fish_completion.install "completions/dotenv.fish"
      end
    end
  end

  def caveats
    <<~EOS
      To use dotenv CLI, you need to authenticate first:
        dotenv login

      For more information, visit:
        https://dotenv.cloud/docs/cli
    EOS
  end

  test do
    system "#{bin}/dotenv", "version"
  end
end
