# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DotenvCli < Formula
  desc "Secure environment variable management CLI"
  homepage "https://dotenv.cloud"
  version "1.3.0"
  license "MIT"

  depends_on "ca-certificates" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dotenvcloud/cli/releases/download/v1.3.0/dotenv-cli_1.3.0_darwin_amd64.tar.gz"
      sha256 "9bd48ec33534b87e7f687dc6dc7310a94d648a2d3fb75df3350ccab85677f5cc"

      define_method(:install) do
        bin.install "dotenv"

        bash_completion.install "completions/dotenv.bash" => "dotenv"
        zsh_completion.install "completions/dotenv.zsh" => "_dotenv"
        fish_completion.install "completions/dotenv.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dotenvcloud/cli/releases/download/v1.3.0/dotenv-cli_1.3.0_darwin_arm64.tar.gz"
      sha256 "fb2130bd7dbfdce8b1f1209247545dea49fe8bb2bd260a34c0e109a7bba59d19"

      define_method(:install) do
        bin.install "dotenv"

        bash_completion.install "completions/dotenv.bash" => "dotenv"
        zsh_completion.install "completions/dotenv.zsh" => "_dotenv"
        fish_completion.install "completions/dotenv.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dotenvcloud/cli/releases/download/v1.3.0/dotenv-cli_1.3.0_linux_amd64.tar.gz"
      sha256 "04bd1a76451359e2f68ec2804620f3f8dfc911046e9208ac51fe359278022761"
      define_method(:install) do
        bin.install "dotenv"

        bash_completion.install "completions/dotenv.bash" => "dotenv"
        zsh_completion.install "completions/dotenv.zsh" => "_dotenv"
        fish_completion.install "completions/dotenv.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dotenvcloud/cli/releases/download/v1.3.0/dotenv-cli_1.3.0_linux_arm64.tar.gz"
      sha256 "c330c21d210013959b8502bbffcda07a051b75214f962b51d80270fb0064e341"
      define_method(:install) do
        bin.install "dotenv"

        bash_completion.install "completions/dotenv.bash" => "dotenv"
        zsh_completion.install "completions/dotenv.zsh" => "_dotenv"
        fish_completion.install "completions/dotenv.fish"
      end
    end
  end

  def caveats
    <<~EOS
      To use dotenv CLI, you need to authenticate first:
        dotenv login

      For more information, visit:
        https://dotenv.cloud/docs/cli
    EOS
  end

  test do
    system "#{bin}/dotenv", "version"
  end
end
