# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DotenvCli < Formula
  desc "Secure environment variable management CLI"
  homepage "https://dotenv.cloud"
  version "1.1.0"
  license "MIT"

  depends_on "ca-certificates" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dotenvcloud/cli/releases/download/v1.1.0/dotenv-cli_1.1.0_darwin_amd64.tar.gz"
      sha256 "f81ec59df696a291cf2b8fdc5a524dbae34c1662ad0ef106eef987cd6384bd8e"

      define_method(:install) do
        bin.install "dotenv"

        bash_completion.install "completions/dotenv.bash" => "dotenv"
        zsh_completion.install "completions/dotenv.zsh" => "_dotenv"
        fish_completion.install "completions/dotenv.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dotenvcloud/cli/releases/download/v1.1.0/dotenv-cli_1.1.0_darwin_arm64.tar.gz"
      sha256 "35e504ae1144bee3a475eeb398956471e6bc7cb93abd02ec33c0c83b2b724319"

      define_method(:install) do
        bin.install "dotenv"

        bash_completion.install "completions/dotenv.bash" => "dotenv"
        zsh_completion.install "completions/dotenv.zsh" => "_dotenv"
        fish_completion.install "completions/dotenv.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dotenvcloud/cli/releases/download/v1.1.0/dotenv-cli_1.1.0_linux_amd64.tar.gz"
      sha256 "e866960910530e1fc27bd03ac057407b5d710098541af7e3b5455d16d795143b"
      define_method(:install) do
        bin.install "dotenv"

        bash_completion.install "completions/dotenv.bash" => "dotenv"
        zsh_completion.install "completions/dotenv.zsh" => "_dotenv"
        fish_completion.install "completions/dotenv.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dotenvcloud/cli/releases/download/v1.1.0/dotenv-cli_1.1.0_linux_arm64.tar.gz"
      sha256 "9121d5eebec71a8be92fc32ff5bc72a217776042be2a9e03675abdff682d4aa2"
      define_method(:install) do
        bin.install "dotenv"

        bash_completion.install "completions/dotenv.bash" => "dotenv"
        zsh_completion.install "completions/dotenv.zsh" => "_dotenv"
        fish_completion.install "completions/dotenv.fish"
      end
    end
  end

  def caveats
    <<~EOS
      To use dotenv CLI, you need to authenticate first:
        dotenv login

      For more information, visit:
        https://dotenv.cloud/docs/cli
    EOS
  end

  test do
    system "#{bin}/dotenv", "version"
  end
end
